include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - backend/**
    - build/**
    - packages/api_client/lib/**
    - packages/admin_api_client/lib/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

plugins:
  lemon_lints:
    path: packages/lemon_lints
