package fm.lemon.tooling.architecture;

import static fm.lemon.tooling.architecture.ToolSupport.JSON;
import static fm.lemon.tooling.architecture.ToolSupport.fail;
import static fm.lemon.tooling.architecture.ToolSupport.slash;

import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.file.Files;
import java.nio.file.Path;

final class DesignTokenGenerator {
  private final Path root;

  DesignTokenGenerator(Path root) {
    this.root = root;
  }

  String generateDart() throws IOException {
    JsonNode colors = readToken("colors.json");
    JsonNode geometry = readToken("geometry.json");
    JsonNode motion = readToken("motion.json");
    JsonNode typography = readToken("typography.json");

    StringBuilder output =
        new StringBuilder("// GENERATED FILE — DO NOT EDIT.\n")
            .append("// Generated by ./lemon generate from design/tokens/*.json.\n\n")
            .append("import 'package:flutter/widgets.dart';\n\n")
            .append("abstract final class LemonColors {\n");
    colors
        .fields()
        .forEachRemaining(
            entry ->
                output
                    .append("  static const Color ")
                    .append(dartIdentifier(entry.getKey()))
                    .append(" = Color(0x")
                    .append(dartColor(entry.getValue().asText()))
                    .append(");\n"));
    output.append("}\n\n");
    appendDoubleTokens(output, "LemonSpacing", geometry.path("spacing"));
    appendDoubleTokens(output, "LemonRadius", geometry.path("radius"));
    appendDoubleTokens(output, "LemonDimensions", geometry.path("dimension"));

    output.append("abstract final class LemonDurations {\n");
    motion
        .path("durationMs")
        .fields()
        .forEachRemaining(
            entry ->
                output
                    .append("  static const Duration ")
                    .append(dartIdentifier(entry.getKey()))
                    .append(" = Duration(milliseconds: ")
                    .append(entry.getValue().intValue())
                    .append(");\n"));
    output.append("}\n\n");
    appendStringTokens(output, "LemonCurves", motion.path("curve"));
    appendDoubleTokens(output, "LemonCelebrationSpring", motion.path("celebrationSpring"));

    output
        .append("final class LemonTextToken {\n")
        .append("  const LemonTextToken({\n")
        .append("    required this.size,\n")
        .append("    required this.lineHeight,\n")
        .append("    required this.weight,\n")
        .append("    this.minimumSize,\n")
        .append("    this.minimumLineHeight,\n")
        .append("  });\n\n")
        .append("  final double size;\n")
        .append("  final double lineHeight;\n")
        .append("  final int weight;\n")
        .append("  final double? minimumSize;\n")
        .append("  final double? minimumLineHeight;\n")
        .append("}\n\n")
        .append("abstract final class LemonTypography {\n");
    typography
        .path("family")
        .fields()
        .forEachRemaining(
            entry ->
                output
                    .append("  static const String ")
                    .append(dartIdentifier(entry.getKey()))
                    .append("Family = '")
                    .append(entry.getValue().asText())
                    .append("';\n"));
    typography
        .path("style")
        .fields()
        .forEachRemaining(
            entry -> {
              JsonNode style = entry.getValue();
              output
                  .append("  static const LemonTextToken ")
                  .append(dartIdentifier(entry.getKey()))
                  .append(" = LemonTextToken(\n")
                  .append("    size: ")
                  .append(style.path("size").asText())
                  .append(",\n    lineHeight: ")
                  .append(style.path("lineHeight").asText())
                  .append(",\n    weight: ")
                  .append(style.path("weight").asText());
              if (style.has("minimumSize")) {
                output
                    .append(",\n    minimumSize: ")
                    .append(style.path("minimumSize").asText())
                    .append(",\n    minimumLineHeight: ")
                    .append(style.path("minimumLineHeight").asText());
              }
              output.append(",\n  );\n");
            });
    return output.append("}\n").toString();
  }

  String generateAndroidGroundColor() throws IOException {
    return """
        <?xml version="1.0" encoding="utf-8"?>
        <!-- GENERATED FILE — DO NOT EDIT. Generated from design/tokens/colors.json. -->
        <resources>
            <color name="lemon_bg0">%s</color>
        </resources>
        """
        .formatted(groundColor());
  }

  String generateIosGroundColor() throws IOException {
    String color = groundColor().substring(1);
    return """
        {
          "colors" : [
            {
              "color" : {
                "color-space" : "srgb",
                "components" : {
                  "alpha" : "1.000000",
                  "blue" : "%s",
                  "green" : "%s",
                  "red" : "%s"
                }
              },
              "idiom" : "universal"
            }
          ],
          "info" : {
            "author" : "lemon-generator",
            "version" : 1
          }
        }
        """
        .formatted(
            iosComponent(color.substring(4, 6)),
            iosComponent(color.substring(2, 4)),
            iosComponent(color.substring(0, 2)));
  }

  String generateWebGroundCss() throws IOException {
    return """
        /* GENERATED FILE — DO NOT EDIT. Generated from design/tokens/colors.json. */
        :root {
          --lemon-bg0: %s;
        }

        html,
        body {
          background-color: var(--lemon-bg0);
        }
        """
        .formatted(groundColor());
  }

  String generateWebManifest(String name, String shortName, String description) throws IOException {
    return """
        {
          "name": "%s",
          "short_name": "%s",
          "start_url": ".",
          "display": "standalone",
          "background_color": "%s",
          "theme_color": "%s",
          "description": "%s",
          "orientation": "portrait-primary",
          "prefer_related_applications": false,
          "icons": [
            {
              "src": "icons/Icon-192.png",
              "sizes": "192x192",
              "type": "image/png"
            },
            {
              "src": "icons/Icon-512.png",
              "sizes": "512x512",
              "type": "image/png"
            },
            {
              "src": "icons/Icon-maskable-192.png",
              "sizes": "192x192",
              "type": "image/png",
              "purpose": "maskable"
            },
            {
              "src": "icons/Icon-maskable-512.png",
              "sizes": "512x512",
              "type": "image/png",
              "purpose": "maskable"
            }
          ]
        }
        """
        .formatted(name, shortName, groundColor(), groundColor(), description);
  }

  private String groundColor() throws IOException {
    String value = readToken("colors.json").path("bg0").asText();
    if (!value.matches("#[0-9A-Fa-f]{6}")) {
      fail("Native launch color requires a six-digit bg0 token, got " + value);
    }
    return value.toUpperCase();
  }

  private static String iosComponent(String hex) {
    return BigDecimal.valueOf(Integer.parseInt(hex, 16))
        .divide(BigDecimal.valueOf(255), 6, RoundingMode.HALF_UP)
        .toPlainString();
  }

  private JsonNode readToken(String name) throws IOException {
    Path path = root.resolve("design/tokens").resolve(name);
    if (!Files.isRegularFile(path)) {
      fail("Missing authored design token file " + slash(root.relativize(path)));
    }
    return JSON.readTree(path.toFile());
  }

  private static void appendDoubleTokens(StringBuilder output, String className, JsonNode values) {
    output.append("abstract final class ").append(className).append(" {\n");
    values
        .fields()
        .forEachRemaining(
            entry ->
                output
                    .append("  static const double ")
                    .append(dartIdentifier(entry.getKey()))
                    .append(" = ")
                    .append(entry.getValue().asText())
                    .append(";\n"));
    output.append("}\n\n");
  }

  private static void appendStringTokens(StringBuilder output, String className, JsonNode values) {
    output.append("abstract final class ").append(className).append(" {\n");
    values
        .fields()
        .forEachRemaining(
            entry ->
                output
                    .append("  static const String ")
                    .append(dartIdentifier(entry.getKey()))
                    .append(" = '")
                    .append(entry.getValue().asText())
                    .append("';\n"));
    output.append("}\n\n");
  }

  private static String dartColor(String value) {
    if (!value.matches("#[0-9A-Fa-f]{6}|#[0-9A-Fa-f]{8}")) {
      fail("Invalid color token " + value);
    }
    String hex = value.substring(1).toUpperCase();
    return hex.length() == 6 ? "FF" + hex : hex;
  }

  private static String dartIdentifier(String value) {
    if (!value.matches("[a-z][A-Za-z0-9]*")) {
      fail("Token name is not a lowerCamel Dart identifier: " + value);
    }
    return value;
  }
}
