name: widgetbook
description: Lemon.fm development-only component shell.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.13.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  lemon_ui:
    path: ../../packages/lemon_ui

flutter:
  uses-material-design: false
